cidr_cram_to_fastq_ref:
    /scratch/ucgd/lustre-labs/quinlan/u6070793/master_files/hg38.fa
elife_cram_to_fastq_ref:
    /scratch/ucgd/lustre/common/data/Reference/homo_sapiens/GRCh38/primary_assembly_decoy_phix.fa
alignment_ref:
    /scratch/ucgd/lustre/common/data/Reference/homo_sapiens/GRCh38/primary_assembly_decoy_phix_masked.fa
bam_to_cram_ref:
    /scratch/ucgd/lustre/common/data/Reference/homo_sapiens/GRCh38/primary_assembly_decoy_phix.fa
