# RE-RUN BEHAVIOR
rerun-incomplete: true
keep-going: true

retries: 0

# CLUSTER BEHAVIOR
executor: slurm
jobs: 96

default-resources:
  slurm_account: "quinlan-rw"
  slurm_partition: "quinlan-shared-rw"
  runtime: 720
  mem_mb: 16000